trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: azure-pipelines-canary-k8s
  dockerRegistryServiceConnection: azure-pipelines-canary-acr1
  imageRepository: 'azure-pipelines-canary-k8s'
  containerRegistry: kelljonsnewacr.azurecr.io #update with container registry
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: app/Dockerfile
        tags: |
          $(tag)

    - publish: manifests
      artifact: manifests

    - publish: misc
      artifact: misc

- stage: DeployCanary
  displayName: Deploy canary
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploycanary
    displayName: Deploy canary
    pool:
      vmImage: ubuntu-latest
    environment: 'akscanary'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@1
            displayName: Create Docker Registry Secret
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'azure-pipelines-canary-acr'
              azureResourceGroup: 'Aksdemo1'
              kubernetesCluster: 'kelljonsAKS'
              secretType: 'dockerRegistry'
              secretName: 'my-acr-secret'
              dockerRegistryEndpoint: 'azure-pipelines-canary-acr1'

          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'aks-connection'
              azureResourceGroup: 'Aksdemo1'
              kubernetesCluster: 'kelljonsAKS'
              strategy: 'canary'
              percentage: '25'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              imagePullSecrets: 'my-acr-secret'

          - task: KubernetesManifest@1
            displayName: Deploy Forbio to Kubernetes cluster
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'aks-connection'
              azureResourceGroup: 'Aksdemo1'
              kubernetesCluster: 'kelljonsAKS'
              manifests: '$(Pipeline.Workspace)/misc/*'
- stage: PromoteRejectCanary
  displayName: Promote or Reject canary
  dependsOn: DeployCanary
  condition: succeeded()

  jobs:
  - deployment: PromoteCanary
    displayName: Promote Canary
    pool: 
      vmImage: ubuntu-latest
    environment: 'akspromote'
    strategy:
      runOnce:
        deploy:
          steps:      
          - task: KubernetesManifest@1
            displayName: Create Docker Registry Secret for akspromote
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'aks-connection'
              azureResourceGroup: 'Aksdemo1'
              kubernetesCluster: 'kelljonsAKS'
              secretType: 'dockerRegistry'
              secretName: 'my-acr-secret'
              dockerRegistryEndpoint: 'azure-pipelines-canary-acr1'

          - task: KubernetesManifest@1
            displayName: promote canary
            inputs:
              action: 'promote'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'aks-connection'
              azureResourceGroup: 'Aksdemo1'
              kubernetesCluster: 'kelljonsAKS'
              strategy: 'canary'
              manifests: '$(Pipeline.Workspace)/manifests/*'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              imagePullSecrets: 'my-acr-secret'


- stage: RejectCanary
  displayName: Reject canary
  dependsOn: PromoteRejectCanary
  condition: failed()

  jobs:
  - deployment: RejectCanary
    displayName: Reject Canary
    pool: 
      vmImage: ubuntu-latest
    environment: 'akscanary'
    strategy:
      runOnce:
        deploy:
          steps:        
          - task: KubernetesManifest@1
            displayName: Create Docker Registry Secret for reject canary
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'aks-connection'
              azureResourceGroup: 'Aksdemo1'
              kubernetesCluster: 'kelljonsAKS'
              secretType: 'dockerRegistry'
              secretName: 'my-acr-secret'
              dockerRegistryEndpoint: 'azure-pipelines-canary-acr1'    
          - task: KubernetesManifest@1
            displayName: Reject canary deployment
            inputs:
              action: 'reject'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'aks-connection'
              azureResourceGroup: 'Aksdemo1'
              kubernetesCluster: 'kelljonsAKS'
              namespace: 'default'
              strategy: 'canary'
              manifests: '$(Pipeline.Workspace)/manifests/*'
